const $=id=>document.getElementById(id);let currentJob=null,lastPreviewSignature=null;
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function status(m,t=''){$('status').className=t;$('status').textContent=m;}
function settings(){return{pageSize:$('pageSize').value,landscape:$('landscape').value==='true',scaleFactor:Number($('scale').value),pageSelection:{mode:$('pageMode').value,customRange:$('customRange').value}};}
function signature(){return currentJob?JSON.stringify({jobId:currentJob.jobId,...settings()}):null;}
function sync(){const valid=Boolean(currentJob&&lastPreviewSignature===signature());$('print').disabled=!valid;$('printHint').hidden=!currentJob||valid;}
function invalidate(){lastPreviewSignature=null;$('exportPdf').disabled=true;sync();if(currentJob)$('previewHint').textContent='Cấu hình đã thay đổi — hãy xem trước lại';}
async function loadPrinters(){try{const ps=await window.printerAPI.getPrinters();$('printer').innerHTML=ps.map(p=>`<option value="${esc(p.name)}" ${p.isDefault?'selected':''}>${esc(p.displayName||p.name)}${p.isDefault?' (Mặc định)':''}</option>`).join('');$('printerState').textContent=`${ps.length} máy in khả dụng`;}catch(e){$('printerState').textContent=e.message;}}
function showFile(name,type,size){$('emptyFile').hidden=true;$('fileChip').hidden=false;$('fileName').textContent=name;$('fileIcon').textContent=type==='pdf'?'📕':'🌐';$('fileMeta').textContent=`${type.toUpperCase()}${size?` · ${(size/1024).toFixed(1)} KB`:''}`;}
function receive(job){currentJob=job;lastPreviewSignature=null;showFile(job.originalName||`HIS-${job.jobId}`,String(job.originalName||'').toLowerCase().endsWith('.pdf')?'pdf':'html');if(job.deviceName)$('printer').value=job.deviceName;if(job.copies)$('copies').value=job.copies;if(job.initialSettings){$('pageSize').value=job.initialSettings.pageSize||'A4';$('landscape').value=String(Boolean(job.initialSettings.landscape));$('scale').value=job.initialSettings.scaleFactor||100;$('pageMode').value=(job.initialSettings.pageSelection&&job.initialSettings.pageSelection.mode)||'all';$('customRange').value=(job.initialSettings.pageSelection&&job.initialSettings.pageSelection.customRange)||'';$('customWrap').hidden=$('pageMode').value!=='custom';}$('docPreview').src='about:blank';$('previewButton').disabled=false;$('exportPdf').disabled=true;$('previewHint').textContent='Chưa xem trước';sync();status('Đã nhận tài liệu. Hãy cấu hình và xem trước trước khi in.');}
async function attachPath(filePath,name,size){const job=await window.printerAPI.createPreview({filePath,deviceName:$('printer').value,copies:$('copies').value});job.originalName=name||job.originalName;receive(job);showFile(name||job.originalName,filePath.toLowerCase().endsWith('.pdf')?'pdf':'html',size);}
window.printerAPI.onVersion(v=>$('version').textContent=`v${v}`);window.printerAPI.onPrintProgress(m=>status(m));window.printerAPI.onIncomingDocument(receive);window.printerAPI.onUpdateStatus(d=>{$('updateStatus').textContent=d.message;});
$('fileDrop').onclick=()=>window.printerAPI.choosePdf().then(p=>p&&attachPath(p));$('fileDrop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('fileDrop').click();}};
['dragenter','dragover'].forEach(n=>$('fileDrop').addEventListener(n,e=>{e.preventDefault();$('fileDrop').classList.add('drag');}));['dragleave','drop'].forEach(n=>$('fileDrop').addEventListener(n,e=>{$('fileDrop').classList.remove('drag');e.preventDefault();}));
$('fileDrop').addEventListener('drop',async e=>{const file=e.dataTransfer.files&&e.dataTransfer.files[0];if(!file)return;const p=window.printerAPI.getPathForFile(file);if(!/\.(pdf|html?|htm)$/i.test(p)){status('Chỉ hỗ trợ PDF, HTML hoặc HTM','error');return;}await attachPath(p,file.name,file.size);});
$('removeFile').onclick=async e=>{e.stopPropagation();if(currentJob)await window.printerAPI.cancelPreview(currentJob.jobId);currentJob=null;lastPreviewSignature=null;$('fileChip').hidden=true;$('emptyFile').hidden=false;$('docPreview').src='about:blank';$('previewButton').disabled=true;$('exportPdf').disabled=true;sync();status('Đã bỏ tài liệu.');};
$('pageMode').onchange=()=>{$('customWrap').hidden=$('pageMode').value!=='custom';invalidate();};['pageSize','landscape'].forEach(id=>$(id).onchange=invalidate);['scale','customRange'].forEach(id=>$(id).oninput=invalidate);
async function adjustScale(delta){const next=Math.min(200,Math.max(50,(Number($('scale').value)||100)+delta));$('scale').value=next;invalidate();status(`Đã ${delta<0?'giảm':'tăng'} tỷ lệ thành ${next}%. Đang tạo bản xem trước...`);if(currentJob&&!$('previewButton').disabled){await previewDocument();}}
$('scaleDown').onclick=()=>adjustScale(-3);$('scaleUp').onclick=()=>adjustScale(3);
async function previewDocument(){if(!currentJob)return;try{$('previewButton').disabled=true;$('scaleDown').disabled=true;$('scaleUp').disabled=true;$('print').disabled=true;$('exportPdf').disabled=true;const sig=signature();status('Đang tạo bản xem trước thực tế...');const result=await window.printerAPI.generatePreview({jobId:currentJob.jobId,settings:settings(),signature:sig});$('docPreview').src=`${result.previewUrl}#toolbar=1&view=FitH`;lastPreviewSignature=sig;$('exportPdf').disabled=false;$('previewHint').textContent='Đúng bản PDF sẽ được gửi tới máy in';sync();status('Đã xem trước thành công. Nút In ngay đã được mở.','ok');}catch(e){lastPreviewSignature=null;$('exportPdf').disabled=true;status(`Lỗi xem trước: ${e.message}`,'error');}finally{$('previewButton').disabled=false;$('scaleDown').disabled=false;$('scaleUp').disabled=false;}}
$('previewButton').onclick=previewDocument;
$('print').onclick=async()=>{const sig=signature();if(!currentJob||sig!==lastPreviewSignature){invalidate();return;}try{$('print').disabled=true;$('previewButton').disabled=true;$('exportPdf').disabled=true;status('Đang in đúng bản đã xem trước...');await window.printerAPI.confirmPreview({jobId:currentJob.jobId,deviceName:$('printer').value,copies:Number($('copies').value)||1,signature:sig});lastPreviewSignature=null;$('previewButton').disabled=false;sync();$('previewHint').textContent='Đã in xong — bấm Xem trước để thao tác tiếp';status('Đã in xong. Nút Xem trước đã được mở lại.','ok');}catch(e){status(`Lỗi in: ${e.message}`,'error');$('previewButton').disabled=false;sync();}};
$('exitForm').onclick=()=>window.printerAPI.exitForm();$('refresh').onclick=loadPrinters;$('update').onclick=()=>window.printerAPI.checkUpdate();
$('exportPdf').onclick=async()=>{if(!currentJob||$('exportPdf').disabled)return;try{const result=await window.printerAPI.exportPdf(currentJob.jobId);if(result.ok)status(`Đã xuất PDF: ${result.filePath}`,'ok');}catch(e){status(`Không xuất được PDF: ${e.message}`,'error');}};

const TEMPLATE_KEY='hisPrintTemplatesV1';
function readTemplates(){try{const value=JSON.parse(localStorage.getItem(TEMPLATE_KEY)||'[]');return Array.isArray(value)?value.map(item=>({...item,hotkey:['F1','F2','F3','F4'].includes(item.hotkey)?'':item.hotkey})):[];}catch{return[];}}
function writeTemplates(items){localStorage.setItem(TEMPLATE_KEY,JSON.stringify(items));renderTemplates(items);}
function templateMessage(message,type=''){$('templateStatus').className=`template-status ${type}`;$('templateStatus').textContent=message;}
function renderTemplates(items=readTemplates()){$('templateList').innerHTML=items.sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(item=>`<option value="${esc(item.name)}" label="${item.hotkey?esc(item.hotkey)+' · ':''}${esc(item.pageSize)}"></option>`).join('');updateTemplateButtons(items);}
function findTemplate(name,items=readTemplates()){const key=String(name||'').trim().toLocaleLowerCase('vi');return items.find(item=>item.name.toLocaleLowerCase('vi')===key);}
function updateTemplateButtons(items=readTemplates()){$('deleteTemplate').disabled=!findTemplate($('selectedTemplate').value,items);}
async function applyTemplate(item){$('selectedTemplate').value=item.name;$('templateSearch').value='';$('templateHotkey').value=item.hotkey||'';$('pageSize').value=item.pageSize;$('landscape').value=String(Boolean(item.landscape));$('pageMode').value=item.pageSelection.mode;$('customRange').value=item.pageSelection.customRange||'';$('scale').value=item.scaleFactor;$('customWrap').hidden=$('pageMode').value!=='custom';updateTemplateButtons();invalidate();templateMessage(`Đã chọn mẫu “${item.name}”${item.hotkey?` (${item.hotkey})`:''}.`,'ok');if(currentJob)$('previewButton').click();}
$('templateSearch').oninput=()=>{};
$('templateSearch').onfocus=()=>{if($('templateSearch').value)$('templateSearch').value='';};
$('templateSearch').onchange=async()=>{const item=findTemplate($('templateSearch').value);if(item)await applyTemplate(item);};
$('saveTemplate').onclick=()=>{const name=$('newTemplateName').value.trim();if(!name){templateMessage('Hãy nhập tên mẫu mới trước khi thêm.','error');$('newTemplateName').focus();return;}const items=readTemplates();if(findTemplate(name,items)){templateMessage(`Tên mẫu “${name}” đã tồn tại. Hãy dùng tên khác hoặc xóa mẫu cũ trước.`,'error');return;}const hotkey=$('templateHotkey').value;const used=hotkey&&items.find(item=>item.hotkey===hotkey);if(used){templateMessage(`Hotkey ${hotkey} đang được mẫu “${used.name}” sử dụng. Hãy chọn hotkey khác hoặc để trống.`,'error');return;}items.push({name,hotkey,...settings()});writeTemplates(items);$('selectedTemplate').value=name;$('templateSearch').value='';$('newTemplateName').value='';updateTemplateButtons(items);templateMessage(`Đã thêm mẫu “${name}”${hotkey?` với hotkey ${hotkey}`:''}.`,'ok');};
$('deleteTemplate').onclick=()=>{const items=readTemplates();const item=findTemplate($('selectedTemplate').value,items);if(!item)return;writeTemplates(items.filter(x=>x!==item));$('selectedTemplate').value='';$('templateSearch').value='';$('templateHotkey').value='';updateTemplateButtons();templateMessage(`Đã xóa mẫu “${item.name}”.`,'ok');};

window.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();window.printerAPI.exitForm();return;}if(event.key==='F1'){event.preventDefault();if(!$('previewButton').disabled)$('previewButton').click();return;}if(event.key==='F2'){event.preventDefault();if(!$('print').disabled)$('print').click();return;}if(event.key==='F3'){event.preventDefault();adjustScale(-3);return;}if(event.key==='F4'){event.preventDefault();adjustScale(3);return;}if(!/^F(?:[5-9]|1[0-2])$/.test(event.key))return;const item=readTemplates().find(template=>template.hotkey===event.key);if(!item)return;event.preventDefault();event.stopPropagation();applyTemplate(item);},true);

renderTemplates();loadPrinters();sync();
