const $=id=>document.getElementById(id);let currentJob=null,lastPreviewSignature=null;
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function status(m,t=''){$('status').className=t;$('status').textContent=m;}
function settings(){return{pageSize:$('pageSize').value,landscape:$('landscape').value==='true',scaleFactor:Number($('scale').value),pageSelection:{mode:$('pageMode').value,customRange:$('customRange').value}};}
function signature(){return currentJob?JSON.stringify({jobId:currentJob.jobId,...settings()}):null;}
function sync(){const valid=Boolean(currentJob&&lastPreviewSignature===signature());$('print').disabled=!valid;$('printHint').hidden=!currentJob||valid;}
function invalidate(){lastPreviewSignature=null;sync();if(currentJob)$('previewHint').textContent='Cấu hình đã thay đổi — hãy xem trước lại';}
async function loadPrinters(){try{const ps=await window.printerAPI.getPrinters();$('printer').innerHTML=ps.map(p=>`<option value="${esc(p.name)}" ${p.isDefault?'selected':''}>${esc(p.displayName||p.name)}${p.isDefault?' (Mặc định)':''}</option>`).join('');$('printerState').textContent=`${ps.length} máy in khả dụng`;}catch(e){$('printerState').textContent=e.message;}}
function showFile(name,type,size){$('emptyFile').hidden=true;$('fileChip').hidden=false;$('fileName').textContent=name;$('fileIcon').textContent=type==='pdf'?'📕':'🌐';$('fileMeta').textContent=`${type.toUpperCase()}${size?` · ${(size/1024).toFixed(1)} KB`:''}`;}
function receive(job){currentJob=job;lastPreviewSignature=null;showFile(job.originalName||`HIS-${job.jobId}`,String(job.originalName||'').toLowerCase().endsWith('.pdf')?'pdf':'html');if(job.deviceName)$('printer').value=job.deviceName;if(job.copies)$('copies').value=job.copies;if(job.initialSettings){$('pageSize').value=job.initialSettings.pageSize||'A4';$('landscape').value=String(Boolean(job.initialSettings.landscape));$('scale').value=job.initialSettings.scaleFactor||100;$('pageMode').value=(job.initialSettings.pageSelection&&job.initialSettings.pageSelection.mode)||'all';$('customRange').value=(job.initialSettings.pageSelection&&job.initialSettings.pageSelection.customRange)||'';$('customWrap').hidden=$('pageMode').value!=='custom';}$('docPreview').src='about:blank';$('previewButton').disabled=false;$('cancel').disabled=false;$('previewHint').textContent='Chưa xem trước';sync();status('Đã nhận tài liệu. Hãy cấu hình và xem trước trước khi in.');}
async function attachPath(filePath,name,size){const job=await window.printerAPI.createPreview({filePath,deviceName:$('printer').value,copies:$('copies').value});job.originalName=name||job.originalName;receive(job);showFile(name||job.originalName,filePath.toLowerCase().endsWith('.pdf')?'pdf':'html',size);}
window.printerAPI.onVersion(v=>$('version').textContent=`v${v}`);window.printerAPI.onPrintProgress(m=>status(m));window.printerAPI.onIncomingDocument(receive);window.printerAPI.onUpdateStatus(d=>{$('updateStatus').textContent=d.message;});
$('fileDrop').onclick=()=>window.printerAPI.choosePdf().then(p=>p&&attachPath(p));$('fileDrop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('fileDrop').click();}};
['dragenter','dragover'].forEach(n=>$('fileDrop').addEventListener(n,e=>{e.preventDefault();$('fileDrop').classList.add('drag');}));['dragleave','drop'].forEach(n=>$('fileDrop').addEventListener(n,e=>{$('fileDrop').classList.remove('drag');e.preventDefault();}));
$('fileDrop').addEventListener('drop',async e=>{const file=e.dataTransfer.files&&e.dataTransfer.files[0];if(!file)return;const p=window.printerAPI.getPathForFile(file);if(!/\.(pdf|html?|htm)$/i.test(p)){status('Chỉ hỗ trợ PDF, HTML hoặc HTM','error');return;}await attachPath(p,file.name,file.size);});
$('removeFile').onclick=async e=>{e.stopPropagation();if(currentJob)await window.printerAPI.cancelPreview(currentJob.jobId);currentJob=null;lastPreviewSignature=null;$('fileChip').hidden=true;$('emptyFile').hidden=false;$('docPreview').src='about:blank';$('previewButton').disabled=true;$('cancel').disabled=true;sync();status('Đã bỏ tài liệu.');};
$('pageMode').onchange=()=>{$('customWrap').hidden=$('pageMode').value!=='custom';invalidate();};['pageSize','landscape'].forEach(id=>$(id).onchange=invalidate);['scale','customRange'].forEach(id=>$(id).oninput=invalidate);
$('previewButton').onclick=async()=>{if(!currentJob)return;try{$('previewButton').disabled=true;$('print').disabled=true;const sig=signature();status('Đang tạo bản xem trước thực tế...');const result=await window.printerAPI.generatePreview({jobId:currentJob.jobId,settings:settings(),signature:sig});$('docPreview').src=`${result.previewUrl}#toolbar=1&view=FitH`;lastPreviewSignature=sig;$('previewHint').textContent='Đúng bản PDF sẽ được gửi tới máy in';sync();status('Đã xem trước thành công. Bạn có thể In ngay.','ok');}catch(e){lastPreviewSignature=null;status(`Lỗi xem trước: ${e.message}`,'error');}finally{$('previewButton').disabled=false;}};
$('print').onclick=async()=>{const sig=signature();if(!currentJob||sig!==lastPreviewSignature){invalidate();return;}try{$('print').disabled=true;status('Đang in đúng bản đã xem trước...');await window.printerAPI.confirmPreview({jobId:currentJob.jobId,deviceName:$('printer').value,copies:Number($('copies').value)||1,signature:sig});status('Đã gửi lệnh in thành công.','ok');currentJob=null;$('previewButton').disabled=true;$('cancel').disabled=true;}catch(e){status(`Lỗi in: ${e.message}`,'error');sync();}};
$('cancel').onclick=()=>currentJob&&window.printerAPI.cancelPreview(currentJob.jobId).then(()=>{$('removeFile').click();});$('refresh').onclick=loadPrinters;$('update').onclick=()=>window.printerAPI.checkUpdate();loadPrinters();sync();
